[package]
name = "ironcamel"
version = "0.2.0"
edition = "2024"


[dependencies]
phf = { version = "0.10", features = ["macros"] }

env_logger = "0.9.0"
log = "0.4.0"
atoi = "2.0.0"

clap = { version = "4.5.53", features = ["derive"] }


inkwell = { version = "0.7.1", features = ["llvm21-1"] }

